#~/project/Project04-CI-CD/roles/jenkins_setup/vars/main.yml (preview 
---
# 젠킨스 관련 변수
# 아이디, 비밀번호, 홈 폴더, 이름을 변경할 수 있습니다.
# roles/jenkins_setup/vars/main.yml
admin_id: "bumseok"
admin_pw: "1234"
jenkins_home: "/home/ansible-admin/jenkins_home"
jenkins_job_name: "Music-Service-Deploy"

# roles/jenkins_setup/vars/main.yml
custom_jenkins_build_path: "/home/ansible-admin/project/Project04-CI-CD-collection/roles/jenkins_setup/files"



