#~/project/Project04-CI-CD/roles/jenkins_setup/vars/main.yml (preview 
---
# roles/jenkins_setup/vars/main.yml
admin_id: "bumseok"
admin_pw: "1234"
jenkins_home: "/home/ansible-admin/jenkins_home"

# 젠킨스 관련 변수
# 아이디, 비밀번호, 홈 폴더, 이름을 변경할 수 있습니다.
jenkins_admin_id: "bumseok"
jenkins_admin_pw: "mypassword123"
jenkins_job_name: "Music-Service-Deploy"


